### ISSUE TITLE
Needham environment needs to use the central Testflinger server

### ISSUE THREAD

**Issue by bladernr** [canonical/testflinger#39] opened 2023-01-11 16:12 UTC
We currently run our own jenkins full stack in Needham.  But for consistency and easy of using testfinger across multiple teams, we need to have our environment talking to the central TF server so that users don't have to worry about --server options when deplyoying machines.

So this is about implementing our card https://warthogs.atlassian.net/browse/SERVCERT-92

**Comment by plars** [comment] 2023-01-11 23:28
I need help understanding what needs to be fixed on the testflinger side here. It sounds like the issue is just that you want to start using the default server for your agents, which shouldn't require any change in testflinger itself, right?

**Comment by plars** [comment] 2023-01-13 20:27
As discussed, closing this since it's tracked elsewhere.

**Closed** 2023-01-13 20:27 UTC
